language: java
sudo: enabled
jdk: openjdk10

before_install:
  - sudo chmod +x scripts/bash/*
  - sudo apt-get install jmeter

jobs:
  include:
  - stage: test
    script:
      - ./scripts/bash/unit-test.sh

  - stage: integration
    script:
      - ./scripts/bash/it-test.sh

#  - stage: performance
#    script: echo "hello world"


