language: java

sudo: enabled

before_install:
  - sudo apt-get install jmeter

jobs:
  include:
  - stage: test
    script:
      - ./scripts/bash/unit-test.sh

  - stage: integration
    script:
      - ./scripts/bash/it-tset.sh

#  - stage: performance
#    script: echo "hello world"


