language: java
sudo: enabled
jdk: openjdk10

before_install:
  - sudo chmod +x scripts/bash/*
  - sudo apt-get install jmeter
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('r00t') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -pr00t
  - sudo service mysql restart

jobs:
  include:
  - stage: test
    script:
      - ./scripts/bash/unit-test.sh

  - stage: integration
    script:
      - ./scripts/bash/it-test.sh

#  - stage: performance
#    script: echo "hello world"


